### ISSUE TITLE
Запуск как службу (демон)

### ISSUE THREAD

**Issue by sosed213** [gh0stwizard/x11mirror-server#2]
Можно ли запустить как службу?
Как ни пробовал не получается. Запускается и тут же останавливается, без ошибок. Успевает принять несколько снимков.

**Comment by gh0stwizard** [comment]
Какая ОС? Если Linux, то используется systemd или вариация openrc? Если не известно (не знаешь как выяснить), то нужно хотя бы название дистрибутива и версия.
Сейчас сервер запускается без режима демона (форка) и ждет остановки процесса путем ввода любого символа. Так было сделано потому что этот проект дефакто демонстрация возможностей, а не полноценный продукт.

**Comment by gh0stwizard** [comment]
Добавил опцию `-d`.

**Comment by sosed213** [comment]
Спасибо!
Система Ubuntu Server 20.04.
Теперь работает как служба (systemd).
